backend:
  name: github
  branch: main
  repo: asmockler/drew-tekulve
  base_url: https://drew-tekulve.vercel.app
  auth_endpoint: api/auth_github
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "project"
    label: "Project"
    folder: "content/projects"
    create: true
    format: json
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: Subtitle, name: subtitle, widget: string, required: false}
      - {label: "Year", name: "year", widget: "string"}
      - {label: Description, name: description, widget: text, required: false}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Video URL", name: "video_url", widget: "string", required: false}
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "project_category"
        value_field: title
        search_fields: ["title"]
      - label: Contributors
        name: contributors
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Role, name: role, widget: string}
      - label: Stills
        name: stills
        widget: list
        fields:
          - {label: Image, name: image, widget: image}
      - {label: "ID", name: "id", widget: "uuid", hint: "This is an autogenerated field. You can ignore it :)"}
  - name: "project_category"
    label: "Project Category"
    folder: "content/project_categories"
    create: true
    format: json
    fields:
      - {label: "Title", name: "title", widget: "string"}
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: home
        file: "content/pages/home.json"
        format: json
        fields:
          - label: "Hero Video URL"
            name: hero_video_url
            widget: string
            hint: "e.g. https://vimeo.com/123456789"
          - label: "Reel Button Text"
            name: reel_button_text
            widget: string
          - label: Projects
            name: projects
            widget: list
            fields:
              - label: Project
                name: project_id
                widget: relation
                collection: project
                options_length: 100
                value_field: id
                display_fields: [title]
                search_fields: [title]
      - label: "Reel Page"
        name: reel
        file: "content/pages/reel.json"
        format: json
        fields:
          - label: "Reel Video URL"
            name: reel_url
            widget: string
          - label: "Reel Cover Image"
            name: reel_cover_image
            widget: image
          - label: Title
            name: title
            widget: string
          - label: "Description"
            name: description
            widget: text
      - label: "About Page"
        name: "about"
        file: "content/pages/about.json"
        format: json
        fields:
          - label: Description
            name: description
            widget: text
          - label: "Client section lead text"
            name: clients_lead
            widget: text
            hint: "This text displays just above the client icons"
          - label: Clients
            name: clients
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Logo, name: logo, widget: image}
          - label: "Contact form lead text"
            name: contact_lead
            widget: text
            hint: "This text displays just above the contact form"
  - name: general
    label: General
    files:
      - label: SEO
        name: seo
        file: "content/general/seo.json"
        format: json
        fields:
          - label: Site Description
            name: description
            widget: string
            hint: "This will be used for the description meta tag e.g. og:description"
          - label: Default social share image
            name: meta_image
            widget: image
            hint: "This image will show when the home and about pages are shared"
      - label: Info
        name: info
        file: "content/general/info.json"
        format: json
        fields:
          - label: Job Title
            name: job_title
            widget: string
            hint: "The title that is displayed in the navbar and footer"
          - label: Email
            name: email
            widget: string
            hint: "The email address used in the mail icon in the footer as well as the destination that contact form responses are sent to"
